version: "3.9"
services:
  easy-panel:
    # platform: "linux/amd64"
    container_name: easy-panel
    ports:
      - "3010:3000"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: easy-panel
    env_file: .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file: .env.docker
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -d outline -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
